runtime: java11
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_instances: 1
  min_pending_latency: 5000ms
  max_pending_latency: automatic
  max_concurrent_requests: 500
  max_idle_instances: 1
  min_idle_instances: 0
env_variables:
  JAVA_USER_OPTS: '-Dspring.profiles.active=prod -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2'
